### ISSUE TITLE
cannot execute binary file

### ISSUE THREAD

**Issue by roveregi** [elk-audio/elkpi-sdk#7]
Hello,
I am struggling to install the toolchain on my machine (Debian 11 on Virualbox, on Win 11 Host 64bits) with the following command:
source elk-glibc-x86_64-elkpi-audio-os-image-cortexa72-raspberrypi4-64-toolchain-0.11.0.sh 

bash: source: elk-glibc-x86_64-elkpi-audio-os-image-cortexa72-raspberrypi4-64-toolchain-0.11.0.sh cannot execute binary file

Do you know where the issue could be here?
Thank you

**Comment by stez-mind** [comment]
Hi,
the `source` command should be done on the environment setup script after running the self-exctracting installer.

In your case, first just run (without source) the installer:
```
$ ./elk-glibc-x86_64-elkpi-audio-os-image-cortexa72-raspberrypi4-64-toolchain-0.11.0.sh
```

and then source the environment setup script from the extracted folder.
